spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/metadb?serverTimezone=Asia/Seoul
    username: batch
    password: batch

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
